### ISSUE TITLE
Brilliant bot

### ISSUE THREAD

**Issue by eatsnails** [NiclasEgeler/DiscordStockTicker#1]
Great BOT and exactly what I was looking for. I am new to Github and coding in general.

The character limit for posts in  Discord are 2000. The Bot will struggle past 9 tickers and then start crashing.

2 options possible to solve this:
1. have the bot start a new post once he receives the 2000 character error message from discord.
2. my favourite option. Rather than set the Channel in config, make it possible for the bot to type in any channel set in the command for instance:
.add GOOG #[channel] 

I would also add the possibility to add multiple tickers in one go by spacing them with a comma.

**Comment by NiclasEgeler** [comment]
Hey,
I rewrote the whole codebase and fixed the issue with discords message character limitation.
Because I still prefer a dedicated channel for my stock updates I'll leave that as is for now. 
Also adding multiple symbols at once and a stock graph will come soon™
If you find any bugs feel free create another Issue.

**Comment by eatsnails** [comment]
Mate this is awesome cannot wait to try it!

What's your discord?

**Comment by NiclasEgeler** [comment]
Xilkon#0001

**Comment by eatsnails** [comment]
https://discord.gg/hWH8Pecm If you want to see your BOT in action. Hopefully when market opens tomorrow it won't crash our server.
